version: '3.5'
services:
  heic-to-jpg:
    build: .
    volumes:
      - .:/app/heic-to-jpg
      - volume-heic-to-jpg-vendor:/app/heic-to-jpg/vendor
    stdin_open: true
    tty: true
volumes:
 volume-heic-to-jpg-vendor:
  name: volume-heic-to-jpg-vendor